### PR TITLE
Character & Citizenship Education -  [Isomer: https://www.zhonghuapri.moe.edu.sg/404.html]: Live (public-facing) site - Others: broken link with '404 page not found - the requested pag...

### PR DESCRIPTION
**Pull request by ISOMERGITHUB33**
From the staging site, the link has been fix. thank you!!

### CODE REVIEW

**Comment by ISOMERGITHUB33** [comment]
{"userId":"3562","message":"ok"}

**Review by Bennylaumunyip — COMMENTED** [review]
ok

**Review by Bennylaumunyip — COMMENTED** [review]
ok

**Review by Bennylaumunyip — COMMENTED** [review]
ok

**Comment by Bennylaumunyip** [comment]
ok

**Comment by Jun-ZPS** [comment]
ok

**Comment by Bennylauu** [comment]
ok

**Review by Bennylauu — COMMENTED** [review]
ok

**Review by Bennylauu — COMMENTED** [review]
ok

**Comment by Bennylauu** [comment]
ok

**Review by Bennylauu — COMMENTED** [review]
ok

**Review by Bennylauu — COMMENTED** [review]
ok

**Review by Bennylauu — COMMENTED** [review]
ok

**Review by Bennylauu — COMMENTED** [review]
ok

**Comment by Bennylauu** [comment]
ok

**Review by isomeradmin — APPROVED** [review]

**Pull request merged**
